version: 2
project_name: httpecho

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}}

release:
  github:
    owner: rbehzadan
    name: httpecho

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

dockers:
  - dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "ghcr.io/rbehzadan/httpecho:{{ .Version }}-amd64"
    - "ghcr.io/rbehzadan/httpecho:latest-amd64"
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  
  - dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "ghcr.io/rbehzadan/httpecho:{{ .Version }}-arm64"
    - "ghcr.io/rbehzadan/httpecho:latest-arm64"
    build_flag_templates:
    - "--platform=linux/arm64"
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  
  - dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
    - "ghcr.io/rbehzadan/httpecho:{{ .Version }}-armv7"
    - "ghcr.io/rbehzadan/httpecho:latest-armv7"
    build_flag_templates:
    - "--platform=linux/arm/v7"
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: ghcr.io/rbehzadan/httpecho:{{ .Version }}
    image_templates:
    - ghcr.io/rbehzadan/httpecho:{{ .Version }}-amd64
    - ghcr.io/rbehzadan/httpecho:{{ .Version }}-arm64
    - ghcr.io/rbehzadan/httpecho:{{ .Version }}-armv7
  
  - name_template: ghcr.io/rbehzadan/httpecho:latest
    image_templates:
    - ghcr.io/rbehzadan/httpecho:latest-amd64
    - ghcr.io/rbehzadan/httpecho:latest-arm64
    - ghcr.io/rbehzadan/httpecho:latest-armv7
